import 'dart:io';
import 'dart:convert';

void main() {
  const total = 600;
  final out = <Map<String, dynamic>>[];

  for (int i = 1; i <= total; i++) {
    out.add({
      'id': i,
      'routeName': 'Screen_${i.toString().padLeft(3, '0')}',
      'title': 'Snaygram Screen #$i',
      'blocks': [
        {'type': 'text', 'value': 'This is autogenerated screen number $i.'},
        {'type': 'image', 'value': 'https://picsum.photos/seed/snaygram$i/800/450'},
        {'type': 'button', 'value': 'Back to Home', 'action': {'type': 'navigate', 'route': '/home'}},
      ],
    });
  }

  // For Flutter, we'll save this as a Dart file instead of JSON
  final buffer = StringBuffer();
  buffer.writeln('const List<Map<String, dynamic>> screenDefinitions = [');
  for (final item in out) {
    buffer.writeln('  $item,');
  }
  buffer.writeln('];');

  File('lib/data/screen_definitions.dart').writeAsStringSync(buffer.toString());
  print('Generated screen definitions for $total screens');
}