name: couldai_user_app
description: "Snaygram Flutter Prototype"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  camera: ^0.10.5+9
  webview_flutter: ^4.8.0
  path_provider: ^2.1.3
  video_player: ^2.8.6
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Light.ttf
          weight: 300