const List<Map<String, dynamic>> screenDefinitions = [
  {
    'id': 1,
    'routeName': 'Screen_001',
    'title': 'Snaygram Screen #1',
    'blocks': [
      {'type': 'text', 'value': 'This is autogenerated screen number 1.'},
      {'type': 'image', 'value': 'https://picsum.photos/seed/snaygram1/800/450'},
      {'type': 'button', 'value': 'Back to Home', 'action': {'type': 'navigate', 'route': '/home'}},
    ],
  },
  {
    'id': 2,
    'routeName': 'Screen_002',
    'title': 'Snaygram Screen #2',
    'blocks': [
      {'type': 'text', 'value': 'This is autogenerated screen number 2.'},
      {'type': 'image', 'value': 'https://picsum.photos/seed/snaygram2/800/450'},
      {'type': 'button', 'value': 'Back to Home', 'action': {'type': 'navigate', 'route': '/home'}},
    ],
  },
  // Add more screen definitions as needed...
];