import 'package:couldai_user_app/models/screen_definition_model.dart';

final List<ScreenDefinition> screenDefinitions = [
  ScreenDefinition(
    id: 1,
    routeName: 'Screen_001',
    title: 'Snaygram Screen #1',
    blocks: [
      ScreenBlock(type: 'text', value: 'This is autogenerated screen number 1.'),
      ScreenBlock(type: 'image', value: 'https://picsum.photos/seed/snaygram1/800/450'),
      ScreenBlock(
        type: 'button',
        value: 'Back to Home',
        action: ScreenAction(type: 'navigate', route: '/home'),
      ),
    ],
  ),
  ScreenDefinition(
    id: 2,
    routeName: 'Screen_002',
    title: 'Snaygram Screen #2',
    blocks: [
      ScreenBlock(type: 'text', value: 'This is autogenerated screen number 2.'),
      ScreenBlock(type: 'image', value: 'https://picsum.photos/seed/snaygram2/800/450'),
      ScreenBlock(
        type: 'button',
        value: 'Back to Home',
        action: ScreenAction(type: 'navigate', route: '/home'),
      ),
    ],
  ),
];
